name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@fused
        with:
          docs-folder: doc/
          conda-environment: doc/environment.yml
          pre-build-command: |-
            rm -rf doc/source/_static
            mkdir -p doc/source/_static
            doxygen Doxyfile
            for file in $(find . -name "*.ipynb")
            do
                # if '.ipynb_checkpoints' not in path
                jupyter nbconvert  --to notebook --output "${file}" --execute "${file}"
            done
            sphinx-apidoc -f -o api `python -c "import teqp; import os; print(os.path.dirname(teqp.__file__))"`
          formats: |-
            epub
            pdf
