name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@fused
        with:
          docs-folder: doc/
          conda-environment: doc/environment.yml
          pre-build-command: |-
            rm -rf doc/source/_static
            && mkdir -p doc/source/_static
            && doxygen Doxyfile
            && sphinx-apidoc -f -o api
#             for glob("**/*.ipynb":
#                 jupyter nbconvert  --to notebook --output {file} --execute {file}
          formats: |-
            epub
            pdf

